---
title: "Tables Binominal Test"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error=TRUE)
library(xglue)
library(forcats)
library(dplyrExtras)
library(here)

dat = readRDS(here("Data","deround_binom_10percent.Rds"))

dat = filter(dat, !mode %in% c("zda.all.pdf","omit.unif"))

dat = dat %>%
  mutate(org.mode = mode) %>%
  mutate_rows(mode=="dsr", mode="DSR") %>%
  mutate_rows(mode=="zda", mode="ZDA") %>%
  mutate_rows(mode=="reported", mode="No adj.") %>%
  mutate_rows(mode=="omit", mode="Omit") %>%
  mutate_rows(mode=="uniform", mode="Uniform")
  
modes = unique(dat$mode)
methods = unique(dat$method)
dat = arrange(dat, desc(h))

tpl = readLines(here("Tex_templates","tab_binom_by_deround_tpl.tex"))
meth.tpl = readLines(here("Tex_templates","tab_binom_by_method_tpl.tex"))

all.dat = dat
p.stars = function(p) {
  res = rep("", length(p))
  res[p<=0.1] = "*"
  res[p<=0.05] = "**"
  res[p<=0.01] = "***"
  res
}

```

# Binominal tests using the 10% significance threshold z=1.645

## All data

```{r results="asis"}
dat = filter(all.dat, method=="ALL")
res = xglue(tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_all.tex"))
res
```


## DID

```{r results="asis"}
dat = filter(all.dat, method=="DID")
res = xglue(tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_did.tex"))
res
```

## IV

```{r results="asis"}
dat = filter(all.dat, method=="IV")
res = xglue(tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_iv.tex"))
res
```


## RDD

```{r results="asis"}
dat = filter(all.dat, method=="RDD")
res = xglue(tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_rdd.tex"))
res
```

## RCT

```{r results="asis"}
dat = filter(all.dat, method=="RCT")
res = xglue(tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_rct.tex"))
res
```

# Tables with the 5 methods next to each other

## No derounding

```{r results="asis"}
dat = filter(all.dat, org.mode=="reported")
res = xglue(meth.tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_reported.tex"))
res

```


## Derounding mode: Omit

```{r results="asis"}
dat = filter(all.dat, org.mode=="omit")
res = xglue(meth.tpl, open="<<", close=">>")
writeLines(res, here("Results", "wp10_binom_omit.tex"))
res

```

